easy_admin:
    site_name: 'TRUCKY'
    design:
        brand_color: 'rgb(225, 19, 19)'
        assets:
            favicon:
                path: 'bundles/frontend/img/trucky.png'
                mime_type: 'image/png'

        menu:
            - label: 'Main'
              icon: 'home'
              children:
                - { label: 'Home page', entity: 'HomePage', default: true }
                - Category
                - Service
                - Contacts
            - { label: 'Contact form', entity: 'ContactForm', icon: 'envelope' }
            - label: 'Special'
              icon: 'user-secret'
              children:
                - Seo
                - User

    entities:
        User:
            class: BackendBundle\Entity\User
        Seo:
            class: BackendBundle\Entity\Seo
            list:
              fields:
                - id
                - slug
                - title
                - h1
                - description
                - keywords
            form:
              fields:
                - { type: 'tab', label: 'Special information', icon: 'puzzle-piece' }
                - { property: 'slug', type_options: { disabled: true }}
                - { property: 'h1', label: 'Tag <h1>' }
                - { type: 'tab', label: 'Meta-tags', icon: 'medium' }
                - title
                - description
                - keywords
        HomePage:
            class: BackendBundle\Entity\HomePage
            list:
              fields:
                - id
                - slider
            form:
              fields:
                - { type: 'tab', label: 'Slider', icon: 'exchange' }
                - { property: 'slider', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewSlide', by_reference: false } }
                - { type: 'tab', label: 'First content block', icon: 'list-ol' }
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
                - { property: 'imageFile', type: 'vich_image' }
                - { type: 'tab', label: 'Second content block', icon: 'list-ol' }
                - { property: 'second_blc_title', label: 'Title'}
                - { property: 'second_blc_sub_title', label: 'Subtitle'}
                - { property: 'second_blc_description', label: 'Description'}
                - { property: 'listName', label: 'List title'}
                - { property: 'list', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }
                - { type: 'tab', label: 'Paralax', css_class: 'col-sm-6', icon: 'image'}
                - { property: 'paralax_blc_title', label: 'Title'}
                - { property: 'paralax_blc_sub_title', label: 'Subtitle'}
                - { property: 'paralax_blc_description', label: 'Description'}
                - { type: 'tab', label: 'Articles', icon: 'exchange' }
                - { property: 'article', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewArticle', by_reference: false } }
        Service:
            class: BackendBundle\Entity\Service
            list:
              fields:
                - id
                - title
                - description
                - published
                - { property: 'image',  type: 'image', base_path: '%app.path.service_images%' }
            form:
              fields:
                - { type: 'tab', label: 'Details', icon: 'puzzle-piece' }
                - { property: 'slug', type_options: { disabled: true }}
                - published
                - { property: 'imageFile', type: 'vich_image' }
                - { type: 'tab', label: 'Basic information', icon: 'cube' }
                - title
                - description
        Category:
            class: BackendBundle\Entity\Category
            list:
              fields:
                - id
                - slug
                - title
            form:
              fields:
                - { property: 'slug', type_options: { disabled: true }}
                - title
        ContactForm:
            class: BackendBundle\Entity\ContactForm
            list:
              fields:
                - id
                - name
                - email
                - telephone
                - body
                - createdAt
            form:
              fields:
                - name
                - email
                - telephone
                - body
                - createdAt
        Contacts:
            class: BackendBundle\Entity\Contacts
            list:
              fields:
                - id
                - title
                - subtitle
                - address
                - email
                - phone
            form:
              fields:
                - title
                - subtitle
                - address
                - email
                - phone