easy_admin:
    site_name: 'TRUCKY'
    design:
        brand_color: 'rgb(225, 19, 19)'
        assets:
            favicon:
                path: 'bundles/frontend/img/trucky.png'
                mime_type: 'image/png'

        menu:
            - label: 'Main'
              icon: 'home'
              children:
                - { label: 'Home page', entity: 'HomePage', default: true }
                - CorporatePhilosophy
                - Equipment
                - Offers
                - Careers
                - Contacts
                - { label: 'Page for Corporate Philosophy', entity: 'AdditionalPage' }
            - label: 'Product'
              children:
                  - Dairy
                  - Produce
                  - SeaFood
                  - Botanic
                  - FrozenMeat
                  - Pharmaceuticals
            - { label: 'Contact form', entity: 'ContactForm', icon: 'envelope' }
            - ApplicationForm
            - label: 'Special'
              icon: 'user-secret'
              children:
                - Seo
                - User

    entities:
        AdditionalPage:
          class: BackendBundle\Entity\AdditionalPage
          list:
            fields:
              - id
              - title
              - sub_title
              - description
          form:
            fields:
              - title
              - sub_title
              - { property: 'description', type: 'ckeditor' }
        User:
            class: BackendBundle\Entity\User
        Seo:
            class: BackendBundle\Entity\Seo
            list:
              fields:
                - id
                - slug
                - title
                - h1
                - description
                - keywords
            form:
              fields:
                - { type: 'tab', label: 'Special information', icon: 'puzzle-piece' }
                - { property: 'slug', type_options: { disabled: true }}
                - { property: 'h1', label: 'Tag <h1>' }
                - { type: 'tab', label: 'Meta-tags', icon: 'medium' }
                - title
                - description
                - keywords
        HomePage:
            class: BackendBundle\Entity\HomePage
            list:
              fields:
                - id
                - slider
            form:
              fields:
                - { type: 'tab', label: 'Slider', icon: 'exchange' }
                - { property: 'slider', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewSlide', by_reference: false } }
                - { type: 'tab', label: 'First content block', icon: 'list-ol' }
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewContentBlock', by_reference: false } }
#                - { property: 'first_blc_title', label: 'Title'}
#                - { property: 'first_blc_sub_title', label: 'Subtitle'}
#                - { property: 'first_blc_description', label: 'Description'}
                - { property: 'imageFile', type: 'vich_image' }
                - { type: 'tab', label: 'Second content block', icon: 'list-ol' }
                - { property: 'second_blc_title', label: 'Title'}
                - { property: 'second_blc_sub_title', label: 'Subtitle'}
                - { property: 'second_blc_description', label: 'Description'}
                - { property: 'listName', label: 'List title'}
                - { property: 'list', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }
                - { type: 'tab', label: 'Paralax', css_class: 'col-sm-6', icon: 'image'}
                - { property: 'paralax_blc_title', label: 'Title'}
                - { property: 'paralax_blc_sub_title', label: 'Subtitle'}
                - { property: 'paralax_blc_description', label: 'Description'}
                - { type: 'tab', label: 'Articles', icon: 'exchange' }
                - { property: 'article', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewArticle', by_reference: false } }
        ContactForm:
            class: BackendBundle\Entity\ContactForm
            list:
              fields:
                - id
                - name
                - email
                - telephone
                - body
                - createdAt
            form:
              fields:
                - name
                - email
                - telephone
                - body
                - createdAt
        ApplicationForm:
            class: BackendBundle\Entity\ApplicationForm
            list:
              fields:
                - id
                - name
                - lastName
                - email
                - telephone
                - createdAt
            form:
              fields:
                - name
                - lastName
                - email
                - telephone
                - city
                - zip
                - experience
                - license
                - driverType
                - preferredHaulType
                - violations
                - accidents
                - distance
                - dui
                - createdAt
        Contacts:
            class: BackendBundle\Entity\Contacts
            list:
              fields:
                - id
                - title
                - subtitle
                - address
                - email
                - phone
            form:
              fields:
                - title
                - subtitle
                - address
                - email
                - phone
        CorporatePhilosophy:
            class: BackendBundle\Entity\CorporatePhilosophy
            list:
              fields:
                - id
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
            form:
              fields:
                - { type: 'tab', label: 'First content block', icon: 'list-ol' }
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
                - { property: 'imageFile', type: 'vich_image' }
                - { type: 'tab', label: 'Second content block', icon: 'list-ol' }
                - { property: 'second_blc_title', label: 'Title'}
                - { property: 'second_blc_sub_title', label: 'Subtitle'}
                - { property: 'second_blc_description', label: 'Description'}
                - { type: 'tab', label: 'List block', icon: 'list-ol' }
                - { property: 'listName', label: 'List title'}
                - { property: 'list', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }
        Equipment:
            class: BackendBundle\Entity\Equipment
            list:
              fields:
                - id
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
            form:
              fields:
                - { type: 'tab', label: 'First content block', icon: 'list-ol' }
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
                - { property: 'imageFile', type: 'vich_image' }
                - { type: 'tab', label: 'Left list', icon: 'list-ol' }
                - { property: 'listName', label: 'List title'}
                - { property: 'list', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItemEq', by_reference: false } }
                - { type: 'tab', label: 'Right list', icon: 'list-ol' }
                - { property: 'listright_blc_title', label: 'Title'}
                - { property: 'listright_blc_sub_title', label: 'Subtitle'}
                - { property: 'listright_blc_description', label: 'Description'}
                - { property: 'listrigth', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewRListItemEq', by_reference: false } }
                - { type: 'tab', label: 'Paralax', css_class: 'col-sm-6', icon: 'image'}
                - { property: 'paralax_blc_title', label: 'Title'}
                - { property: 'paralax_blc_sub_title', label: 'Subtitle'}
                - { property: 'paralax_blc_description', label: 'Description'}
                - { type: 'tab', label: 'Block after paralax', icon: 'list-ol' }
                - { property: 'second_blc_title', label: 'Title'}
                - { property: 'second_blc_sub_title', label: 'Subtitle'}
                - { property: 'second_blc_description', label: 'Description'}
        Offers:
            class: BackendBundle\Entity\Offers
            list:
              fields:
                - id
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
            form:
              fields:
                - { type: 'tab', label: 'First content block', icon: 'list-ol' }
                - { property: 'first_blc_title', label: 'Title'}
                - { property: 'first_blc_sub_title', label: 'Subtitle'}
                - { property: 'first_blc_description', label: 'Description'}
                - { property: 'imageFile', type: 'vich_image' }
                - { type: 'tab', label: 'Left list', icon: 'list-ol' }
                - { property: 'listName', label: 'List title'}
                - { property: 'list', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false }}
                - { type: 'tab', label: 'Right list', icon: 'list-ol' }
                - { property: 'listright_blc_title', label: 'Title'}
                - { property: 'listright_blc_sub_title', label: 'Subtitle'}
                - { property: 'listright_blc_description', label: 'Description'}
                - { property: 'listrigth', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false }}
                - { type: 'tab', label: 'Articles', icon: 'exchange' }
                - { property: 'article', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewArticle', by_reference: false }}
        Dairy:
            class: BackendBundle\Entity\Dairy
            list:
              fields:
                - id
                - title
            form:
              fields:
                - title
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewProductContentBlock', by_reference: false }}
        Produce:
            class: BackendBundle\Entity\Produce
            list:
              fields:
                - id
                - title
            form:
              fields:
                - title
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewProductContentBlock', by_reference: false }}
        SeaFood:
            class: BackendBundle\Entity\SeaFood
            list:
              fields:
                - id
                - title
            form:
              fields:
                - title
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewProductContentBlock', by_reference: false }}
        Botanic:
            class: BackendBundle\Entity\Botanic
            list:
              fields:
                - id
                - title
            form:
              fields:
                - title
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewProductContentBlock', by_reference: false }}
        FrozenMeat:
            class: BackendBundle\Entity\FrozenMeat
            list:
              fields:
                - id
                - title
            form:
              fields:
                - title
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewProductContentBlock', by_reference: false }}
        Pharmaceuticals:
            class: BackendBundle\Entity\Pharmaceuticals
            list:
              fields:
                - id
                - title
            form:
              fields:
                - title
                - { property: 'contentBlock', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewProductContentBlock', by_reference: false }}
        Careers:
          class: BackendBundle\Entity\Careers
          list:
            fields:
              - id
              - { property: 'first_blc_title', label: 'Title'}
              - { property: 'first_blc_sub_title', label: 'Subtitle'}
              - { property: 'first_blc_description', label: 'Description'}
          form:
            fields:
              - { type: 'tab', label: 'First content block', icon: 'list-ol' }
              - { property: 'first_blc_title', label: 'Title'}
              - { property: 'first_blc_sub_title', label: 'Subtitle'}
              - { property: 'first_blc_description', label: 'Description'}
              - { property: 'imageFile', type: 'vich_image' }
              - { type: 'tab', label: 'Second content block', icon: 'list-ol' }
              - { property: 'second_blc_title', label: 'Title'}
              - { property: 'second_blc_sub_title', label: 'Subtitle'}
              - { property: 'second_blc_description', label: 'Description'}
              - { type: 'tab', label: 'List block', icon: 'list-ol' }
              - { property: 'listMainTitle', label: 'List main title'}
              - { property: 'listName', label: 'List title'}
              - { property: 'list', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }
              - { type: 'tab', label: 'List block', icon: 'list-ol' }
              - { property: 'listName2', label: 'List title'}
              - { property: 'list2', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }
              - { type: 'tab', label: 'List block', icon: 'list-ol' }
              - { property: 'listName3', label: 'List title'}
              - { property: 'list3', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }
              - { type: 'tab', label: 'List block', icon: 'list-ol' }
              - { property: 'listName4', label: 'List title'}
              - { property: 'list4', type: 'collection', type_options: { entry_type: 'BackendBundle\Form\Type\AddNewItem', by_reference: false } }